Repository unsignedapps/Vexil, pull requests merged in 2020-11, with the labels that each got.

#67 Fixed issue on iOS where FlagGroup's displayed as sections were being nested inside SwiftUI Section views, causing rendering issues
  Sources/Vexillographer/FlagGroupView.swift
Labels: bug, ios, vexillographer

#68 Updated the matrix of supported Xcode / OS versions to include the November releases
  .github/workflows/ios-tests.yml
  .github/workflows/linux-tests.yml
  .github/workflows/macos-tests.yml
  .github/workflows/tvos-tests.yml
  .github/workflows/watchos-tests.yml
Labels: ci, patch

#69 Improve section-styled FlagGroup display
  Sources/Vexillographer/FlagGroupView.swift
  Sources/Vexillographer/FlagSectionView.swift
  Sources/Vexillographer/Unfurling/UnfurledFlag.swift
  Sources/Vexillographer/Unfurling/UnfurledFlagGroup.swift
  Sources/Vexillographer/Unfurling/UnfurledFlagItem.swift
  Sources/Vexillographer/Vexillographer.swift
Labels: bug, enhancement, patch
